// src/app/components/TestCaseManager.tsx
import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "./ui/dialog";
import { Badge } from "./ui/badge";
import { Textarea } from "./ui/textarea";
import { Plus, Search, Pencil, Trash2, Play, Copy, Code } from 'lucide-react';

interface TestCase {
  id: string;
  name: string;
  type: 'API' | 'WEB' | 'APP';
  description: string;
  environment: string;
  status: 'active' | 'inactive';
  lastRun?: string;
  result?: 'success' | 'failed' | 'pending';
}

const mockTestCases: TestCase[] = [
  {
    id: '1',
    name: '用户登录接口测试',
    type: 'API',
    description: '测试用户登录接口的正常流程和异常情况',
    environment: 'production',
    status: 'active',
    lastRun: '2026-01-02 10:30',
    result: 'success'
  },
  {
    id: '2',
    name: 'Web首页功能测试',
    type: 'WEB',
    description: '测试Web首页的关键功能和交互',
    environment: 'staging',
    status: 'active',
    lastRun: '2026-01-02 09:15',
    result: 'success'
  },
  {
    id: '3',
    name: 'APP支付流程测试',
    type: 'APP',
    description: '测试APP端的支付流程',
    environment: 'production',
    status: 'active',
    lastRun: '2026-01-01 18:20',
    result: 'failed'
  }
];

export function TestCaseManager() {
  const [testCases, setTestCases] = useState<TestCase[]>(mockTestCases);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState<string>('all');
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [selectedTestCase, setSelectedTestCase] = useState<TestCase | null>(null);

  const filteredTestCases = testCases.filter(tc => {
    const matchesSearch = tc.name.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = filterType === 'all' || tc.type === filterType;
    return matchesSearch && matchesType;
  });

  const getResultBadge = (result?: string) => {
    switch (result) {
      case 'success':
        return <Badge className="bg-green-500">成功</Badge>;
      case 'failed':
        return <Badge className="bg-red-500">失败</Badge>;
      case 'pending':
        return <Badge className="bg-yellow-500">待执行</Badge>;
      default:
        return <Badge variant="outline">未运行</Badge>;
    }
  };

  const getTypeBadge = (type: string) => {
    const colors = {
      'API': 'bg-blue-100 text-blue-800',
      'WEB': 'bg-purple-100 text-purple-800',
      'APP': 'bg-green-100 text-green-800'
    };
    return <Badge className={colors[type as keyof typeof colors]}>{type}</Badge>;
  };

  return (
    <div className="space-y-6">
      {/* Search and Filter Bar */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
              <Input
                placeholder="搜索测试用例..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={filterType} onValueChange={setFilterType}>
              <SelectTrigger className="w-full md:w-[180px]">
                <SelectValue placeholder="用例类型" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">全部类型</SelectItem>
                <SelectItem value="API">API测试</SelectItem>
                <SelectItem value="WEB">WEB测试</SelectItem>
                <SelectItem value="APP">APP测试</SelectItem>
              </SelectContent>
            </Select>
            <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
              <DialogTrigger asChild>
                <Button className="w-full md:w-auto">
                  <Plus className="w-4 h-4 mr-2" />
                  新建用例
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl">
                <DialogHeader>
                  <DialogTitle>创建测试用例</DialogTitle>
                  <DialogDescription>
                    填写测试用例的基本信息和测试步骤
                  </DialogDescription>
                </DialogHeader>
                <CreateTestCaseForm onClose={() => setIsCreateDialogOpen(false)} />
              </DialogContent>
            </Dialog>
          </div>
        </CardContent>
      </Card>

      {/* Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-gray-600">总用例数</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-semibold">{testCases.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-gray-600">API用例</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-semibold text-blue-600">
              {testCases.filter(tc => tc.type === 'API').length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-gray-600">WEB用例</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-semibold text-purple-600">
              {testCases.filter(tc => tc.type === 'WEB').length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-gray-600">APP用例</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-semibold text-green-600">
              {testCases.filter(tc => tc.type === 'APP').length}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Test Cases List */}
      <Card>
        <CardHeader>
          <CardTitle>测试用例列表</CardTitle>
          <CardDescription>管理和执行所有测试用例</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {filteredTestCases.map((testCase) => (
              <Card key={testCase.id} className="hover:shadow-md transition-shadow">
                <CardContent className="pt-6">
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <h3 className="font-semibold">{testCase.name}</h3>
                        {getTypeBadge(testCase.type)}
                        {testCase.result && getResultBadge(testCase.result)}
                      </div>
                      <p className="text-sm text-gray-600 mb-2">{testCase.description}</p>
                      <div className="flex items-center gap-4 text-xs text-gray-500">
                        <span>环境: {testCase.environment}</span>
                        {testCase.lastRun && <span>最后运行: {testCase.lastRun}</span>}
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" onClick={() => setSelectedTestCase(testCase)}>
                        <Play className="w-4 h-4" />
                      </Button>
                      <Button variant="outline" size="sm">
                        <Pencil className="w-4 h-4" />
                      </Button>
                      <Button variant="outline" size="sm">
                        <Copy className="w-4 h-4" />
                      </Button>
                      <Button variant="outline" size="sm" className="text-red-600 hover:text-red-700">
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function CreateTestCaseForm({ onClose }: { onClose: () => void }) {
  const [testType, setTestType] = useState<string>('API');

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label>用例名称</Label>
          <Input placeholder="输入用例名称" />
        </div>
        <div className="space-y-2">
          <Label>用例类型</Label>
          <Select value={testType} onValueChange={setTestType}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="API">API测试</SelectItem>
              <SelectItem value="WEB">WEB测试</SelectItem>
              <SelectItem value="APP">APP测试</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="space-y-2">
        <Label>用例描述</Label>
        <Textarea placeholder="描述测试用例的目的和范围" rows={3} />
      </div>

      <div className="space-y-2">
        <Label>运行环境</Label>
        <Select>
          <SelectTrigger>
            <SelectValue placeholder="选择运行环境" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="dev">开发环境</SelectItem>
            <SelectItem value="staging">测试环境</SelectItem>
            <SelectItem value="production">生产环境</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <Tabs defaultValue="steps" className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="steps">测试步骤</TabsTrigger>
          <TabsTrigger value="assertions">断言规则</TabsTrigger>
          <TabsTrigger value="params">参数配置</TabsTrigger>
        </TabsList>
        <TabsContent value="steps" className="space-y-4">
          {testType === 'API' && (
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>请求方法</Label>
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder="选择请求方法" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="GET">GET</SelectItem>
                    <SelectItem value="POST">POST</SelectItem>
                    <SelectItem value="PUT">PUT</SelectItem>
                    <SelectItem value="DELETE">DELETE</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>接口地址</Label>
                <Input placeholder="/api/users/login" />
              </div>
              <div className="space-y-2">
                <Label>请求体</Label>
                <Textarea placeholder='{"username": "test", "password": "123456"}' rows={4} className="font-mono text-sm" />
              </div>
            </div>
          )}
          {testType === 'WEB' && (
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>关键字驱动步骤</Label>
                <Textarea 
                  placeholder="输入URL: https://example.com&#10;点击元素: #login-btn&#10;输入文本: #username, testuser&#10;输入文本: #password, 123456&#10;点击元素: #submit" 
                  rows={6}
                />
              </div>
            </div>
          )}
          {testType === 'APP' && (
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>应用包名</Label>
                <Input placeholder="com.example.app" />
              </div>
              <div className="space-y-2">
                <Label>关键字驱动步骤</Label>
                <Textarea 
                  placeholder="启动应用: com.example.app&#10;点击元素: resource-id=login_btn&#10;输入文本: resource-id=username, testuser&#10;输入文本: resource-id=password, 123456&#10;点击元素: resource-id=submit" 
                  rows={6}
                />
              </div>
            </div>
          )}
        </TabsContent>
        <TabsContent value="assertions" className="space-y-4">
          <div className="space-y-2">
            <Label>断言规则</Label>
            <Textarea 
              placeholder="状态码等于: 200&#10;响应时间小于: 1000ms&#10;JSON路径存在: $.data.token&#10;JSON路径等于: $.data.status, success" 
              rows={6}
            />
          </div>
        </TabsContent>
        <TabsContent value="params" className="space-y-4">
          <div className="space-y-2">
            <Label>公共参数</Label>
            <Textarea 
              placeholder="变量名: 变量值&#10;base_url: https://api.example.com&#10;api_key: ${API_KEY}&#10;timestamp: ${random.timestamp()}" 
              rows={6}
            />
          </div>
        </TabsContent>
      </Tabs>

      <div className="flex justify-end gap-2 pt-4">
        <Button variant="outline" onClick={onClose}>
          取消
        </Button>
        <Button onClick={onClose}>
          创建用例
        </Button>
      </div>
    </div>
  );
}

// platform-frontend/src/views/TestCaseManager.vue
<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import { Card, CardContent } from '@/components/ui/card'
import Button from '@/components/ui/button/Button.vue'
import Input from '@/components/ui/input/Input.vue'
import Badge from '@/components/ui/badge/Badge.vue'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import Label from '@/components/ui/label/Label.vue'
import { Search, Plus, Pencil, Trash2, Play, Code } from 'lucide-vue-next'
import request from '@/api/request'

const router = useRouter()

interface TestCase {
  id: string;
  name: string;
  type: 'API' | 'WEB' | 'APP';
  description: string;
  environment: string;
  status: 'active' | 'inactive';
  lastRun?: string;
  lastResult?: 'success' | 'failed' | 'pending';
}

const testCases = ref<TestCase[]>([])
const loading = ref(false)
const searchTerm = ref('')
const filterType = ref('all')
const editDialogOpen = ref(false)
const editingCase = ref<TestCase | null>(null)

const fetchTestCases = async () => {
  loading.value = true
  try {
    const res: any = await request.get('/testcases', {
      params: {
        keyword: searchTerm.value.trim(),
        type: filterType.value === 'all' ? undefined : filterType.value
      }
    })
    // Handle Mybatis Plus Page result: { records: [], total: ... }
    if (res && res.records) {
        testCases.value = res.records
    } else if (Array.isArray(res)) {
        testCases.value = res
    }
  } catch (e) {
    console.error('Failed to fetch test cases', e)
  } finally {
    loading.value = false
  }
}

const resetFilters = () => {
  searchTerm.value = ''
  filterType.value = 'all'
  fetchTestCases()
}

const handleDelete = async (id: string) => {
  if (!confirm('确定要删除这个测试用例吗？')) return
  try {
    await request.delete(`/testcases/${id}`)
    await fetchTestCases()
  } catch (e) {
    alert('删除失败')
  }
}

const handleRun = async (id: string) => {
    try {
        const res: any = await request.post(`/testcases/${id}/execute`)
        await fetchTestCases()
        if (res?.status === 'success') {
            alert('执行成功')
        } else {
            alert(res?.error || '执行失败')
        }
    } catch (e: any) {
        alert(e?.message || '执行失败')
    }
}

const navigateToEditor = (id: string, type: string) => {
    if (type === 'API') {
        router.push(`/api-test/edit/${id}`)
    } else {
        router.push(`/web-app?id=${id}`) // ScriptEditor uses query param or we can change route
    }
}

const handleEdit = (id: string) => {
    const testCase = testCases.value.find(c => c.id === id)
    if (testCase) {
        editingCase.value = { ...testCase } // Clone to avoid direct mutation
        editDialogOpen.value = true
    }
}

const handleCode = (id: string) => {
    const testCase = testCases.value.find(c => c.id === id)
    if (testCase) {
        navigateToEditor(id, testCase.type)
    }
}

const handleSaveEdit = async () => {
    if (!editingCase.value) return
    try {
        await request.put('/testcases', editingCase.value)
        editDialogOpen.value = false
        fetchTestCases()
        alert('保存成功')
    } catch (e) {
        alert('保存失败')
    }
}

const handleCreate = () => {
    // Default to creating API case, user can change type?
    // Or navigate to a create selection page.
    // Given the UI, we'll go to API editor for now as it's the main one.
    router.push('/api-test/edit')
}

onMounted(() => {
  fetchTestCases()
})

watch([searchTerm, filterType], () => {
  fetchTestCases()
})

const filteredTestCases = computed(() => {
  const normalizedSearch = searchTerm.value.trim().toLowerCase()
  return testCases.value.filter(tc => {
    const name = (tc.name || '').toLowerCase()
    const matchesSearch = normalizedSearch === '' || name.includes(normalizedSearch)
    const matchesType = filterType.value === 'all' || tc.type === filterType.value
    return matchesSearch && matchesType
  })
})

const getResultBadgeColor = (result?: string) => {
  switch (result) {
    case 'success': return 'bg-green-500 hover:bg-green-600'
    case 'failed': return 'bg-red-500 hover:bg-red-600'
    case 'pending': return 'bg-yellow-500 hover:bg-yellow-600'
    default: return ''
  }
}

const getResultText = (result?: string) => {
  switch (result) {
    case 'success': return '成功'
    case 'failed': return '失败'
    case 'pending': return '待执行'
    default: return '未运行'
  }
}

const getTypeBadgeClass = (type: string) => {
  const colors: Record<string, string> = {
    'API': 'bg-blue-100 text-blue-800 hover:bg-blue-200',
    'WEB': 'bg-purple-100 text-purple-800 hover:bg-purple-200',
    'APP': 'bg-green-100 text-green-800 hover:bg-green-200'
  }
  return colors[type] || ''
}
</script>

<template>
  <div class="space-y-6 p-6">
    <Dialog v-model:open="editDialogOpen">
      <DialogContent class="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>编辑测试用例</DialogTitle>
          <DialogDescription>修改测试用例信息</DialogDescription>
        </DialogHeader>
        <div class="grid gap-4 py-4" v-if="editingCase">
          <div class="grid grid-cols-4 items-center gap-4">
            <Label class="text-right">名称</Label>
            <Input v-model="editingCase.name" class="col-span-3" />
          </div>
          <div class="grid grid-cols-4 items-center gap-4">
            <Label class="text-right">类型</Label>
            <Select v-model="editingCase.type">
              <SelectTrigger class="col-span-3">
                <SelectValue placeholder="选择类型" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="API">API 接口测试</SelectItem>
                <SelectItem value="WEB">Web 自动化</SelectItem>
                <SelectItem value="APP">App 自动化</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div class="grid grid-cols-4 items-center gap-4">
            <Label class="text-right">环境</Label>
            <Input v-model="editingCase.environment" class="col-span-3" />
          </div>
          <div class="grid grid-cols-4 items-center gap-4">
            <Label class="text-right">描述</Label>
            <Input v-model="editingCase.description" class="col-span-3" />
          </div>
        </div>
        <div class="flex justify-end">
          <Button @click="handleSaveEdit">保存</Button>
        </div>
      </DialogContent>
    </Dialog>

    <!-- Search and Filter Bar -->
    <div class="flex items-center justify-between gap-4 bg-white p-4 rounded-lg shadow-sm border border-gray-100">
      <div class="flex items-center gap-4 flex-1">
        <div class="relative flex-1 max-w-md">
          <Search class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-4 h-4" />
          <Input v-model="searchTerm" placeholder="搜索测试用例..." class="pl-9" />
        </div>
        <Button variant="outline" @click="resetFilters">重置</Button>
        <Select v-model="filterType">
          <SelectTrigger class="w-[180px]">
            <SelectValue placeholder="所有类型" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">所有类型</SelectItem>
            <SelectItem value="API">API 接口测试</SelectItem>
            <SelectItem value="WEB">Web 自动化</SelectItem>
            <SelectItem value="APP">App 自动化</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <Button @click="handleCreate">
        <Plus class="w-4 h-4 mr-2" />
        新建API测试用例
      </Button>
    </div>

    <!-- Test Cases List -->
    <div class="space-y-4">
      <Card v-for="testCase in filteredTestCases" :key="testCase.id" class="hover:shadow-md transition-shadow">
        <CardContent class="p-6">
          <div class="flex items-center justify-between">
            <div class="space-y-1">
              <div class="flex items-center gap-3">
                <h3 class="font-semibold text-lg text-gray-900">{{ testCase.name }}</h3>
                <Badge :class="getTypeBadgeClass(testCase.type)">
                  {{ testCase.type }}
                </Badge>
                <Badge variant="outline" class="text-xs">
                  {{ testCase.environment }}
                </Badge>
                <Badge v-if="testCase.lastResult" :class="getResultBadgeColor(testCase.lastResult) + ' text-white border-0'">
                  {{ getResultText(testCase.lastResult) }}
                </Badge>
              </div>
              <p class="text-sm text-gray-500">{{ testCase.description }}</p>
              <div class="flex items-center gap-4 text-xs text-gray-400 mt-2">
                <span>ID: {{ testCase.id }}</span>
                <span v-if="testCase.lastRun">最后运行: {{ testCase.lastRun }}</span>
              </div>
            </div>
            
            <div class="flex items-center gap-2">
              <Button variant="ghost" size="icon" class="text-green-600 hover:text-green-700 hover:bg-green-50" @click="handleRun(testCase.id)">
                <Play class="w-4 h-4" />
              </Button>
              <Button variant="ghost" size="icon" class="text-blue-600 hover:text-blue-700 hover:bg-blue-50" @click="handleEdit(testCase.id)">
                <Pencil class="w-4 h-4" />
              </Button>
              <Button variant="ghost" size="icon" class="text-purple-600 hover:text-purple-700 hover:bg-purple-50" @click="handleCode(testCase.id)">
                <Code class="w-4 h-4" />
              </Button>
              <Button variant="ghost" size="icon" class="text-red-600 hover:text-red-700 hover:bg-red-50" @click="handleDelete(testCase.id)">
                <Trash2 class="w-4 h-4" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
      
      <!-- Empty State -->
      <div v-if="filteredTestCases.length === 0 && !loading" class="text-center py-12 text-gray-500 bg-white rounded-lg border border-dashed border-gray-200">
        <div class="flex justify-center mb-4">
          <Search class="w-12 h-12 text-gray-300" />
        </div>
        <p>没有找到匹配的测试用例</p>
      </div>
    </div>
  </div>
</template>
