// platform-frontend/src/views/ReportDetail.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { Card, CardContent } from '@/components/ui/card'
import Badge from '@/components/ui/badge/Badge.vue'
import Button from '@/components/ui/button/Button.vue'
import { CheckCircle, XCircle, Clock, Download, Share2, AlertCircle } from 'lucide-vue-next'
import request from '@/api/request'

type LogLevel = 'info' | 'success' | 'error'

interface ReportDetail {
  id: number
  planId?: number | null
  caseId?: number | null
  caseName?: string | null
  caseType?: string | null
  status?: string | null
  executionTime?: number | null
  logs?: string | null
  executedAt?: string | null
  executedBy?: string | null
  environment?: string | null
}

interface ConsoleLog {
  time: string
  level: LogLevel
  message: string
}

interface ExecutionStep {
  step: number
  action: string
  status: 'success' | 'failed'
  time: string
  details: string
  error?: boolean
}

interface RawTestCase {
  id: number
  type?: string | null
  content?: string | null
  name?: string | null
  description?: string | null
  environment?: string | null
}

const route = useRoute()
const report = ref<ReportDetail | null>(null)
const testCase = ref<RawTestCase | null>(null)

const parsedCaseContent = computed(() => {
  if (!testCase.value || !testCase.value.content) {
    return null as unknown
  }
  const raw = String(testCase.value.content).trim()
  if (!raw) {
    return null as unknown
  }
  try {
    return JSON.parse(raw) as unknown
  } catch {
    return raw as unknown
  }
})

const logLines = computed(() => {
  if (!report.value || !report.value.logs) {
    return [] as string[]
  }
  return String(report.value.logs)
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
})

const consoleLogs = computed<ConsoleLog[]>(() => {
  if (!logLines.value.length) {
    return []
  }
  return logLines.value.map((line, index) => {
    const lower = line.toLowerCase()
    let level: LogLevel = 'info'
    if (/(error|失败|异常|fail)/i.test(lower)) {
      level = 'error'
    } else if (/(success|成功|pass|通过|ok)/i.test(lower)) {
      level = 'success'
    }
    return {
      time: `${index + 1}`.padStart(2, '0'),
      level,
      message: line
    }
  })
})

const apiErrorText = computed(() => {
  const lines = logLines.value
  if (!lines.length) {
    return ''
  }
  const found = lines.find((line) => /assert/i.test(line)) || ''
  return found
})

function applyStepStatuses(
  steps: ExecutionStep[],
  executedCount: number,
  isSuccess: boolean
): ExecutionStep[] {
  if (!steps.length) {
    return steps
  }
  if (isSuccess) {
    return steps.map((s) => ({
      ...s,
      status: 'success',
      error: false
    }))
  }
  const total = steps.length
  const executed = Math.max(0, Math.min(executedCount, total))
  const failIndex = executed < total ? executed : total - 1
  return steps.map((s, idx) => {
    if (idx < executed) {
      return {
        ...s,
        status: 'success',
        error: false
      }
    }
    if (idx === failIndex) {
      return {
        ...s,
        status: 'failed',
        error: true
      }
    }
    return {
      ...s,
      status: 'failed',
      error: false
    }
  })
}

function buildApiSteps(
  content: any,
  isSuccess: boolean,
  errorText: string
): ExecutionStep[] {
  const steps: ExecutionStep[] = []
  if (!content || typeof content !== 'object') {
    return steps
  }
  const method = String((content.method || 'GET') as string).toUpperCase()
  const url = String(content.url || '')
  let index = 1
  steps.push({
    step: index++,
    action: `发送请求 ${method} ${url}`,
    status: 'success',
    time: '',
    details: `Method: ${method} URL: ${url}`,
    error: false
  })
  const assertions = Array.isArray(content.assertions)
    ? content.assertions
    : []
  const activeAssertions = assertions.filter(
    (a: any) => a && a.active !== false
  )
  assertions.forEach((a: any) => {
    if (!a || (a.active === false)) {
      return
    }
    const t = String(a.type || '').toLowerCase()
    if (t === 'status') {
      const expected = a.value
      steps.push({
        step: index++,
        action: '断言状态码',
        status: 'success',
        time: '',
        details: `期望状态码 = ${expected}`,
        error: false
      })
    } else if (t === 'json') {
      const path = a.path
      const expected = a.value
      steps.push({
        step: index++,
        action: '断言 JSON 字段',
        status: 'success',
        time: '',
        details: `路径 ${path} = ${JSON.stringify(expected)}`,
        error: false
      })
    }
  })
  if (isSuccess || !activeAssertions.length) {
    return steps.map((s) => ({
      ...s,
      status: 'success',
      error: false
    }))
  }
  let failIndex = -1
  const lower = errorText.toLowerCase()
  if (lower.startsWith('status assert failed')) {
    const match = errorText.match(/expected\s+(\d+)/i)
    const expected = match ? match[1] : null
    if (expected != null) {
      activeAssertions.forEach((a: any, idx: number) => {
        if (
          String((a.type || '')).toLowerCase() === 'status' &&
          String(a.value) === expected &&
          failIndex < 0
        ) {
          failIndex = 1 + idx
        }
      })
    }
  } else if (lower.startsWith('json assert failed at')) {
    const match = errorText.match(/at\s+(.+)$/i)
    const path = match ? match[1].trim() : ''
    if (path) {
      activeAssertions.forEach((a: any, idx: number) => {
        if (
          String((a.type || '')).toLowerCase() === 'json' &&
          String(a.path || '') === path &&
          failIndex < 0
        ) {
          failIndex = 1 + idx
        }
      })
    }
  } else if (lower.startsWith('json assert error')) {
    activeAssertions.forEach((a: any, idx: number) => {
      if (
        String((a.type || '')).toLowerCase() === 'json' &&
        failIndex < 0
      ) {
        failIndex = 1 + idx
      }
    })
  } else if (lower.startsWith('time assert failed')) {
    activeAssertions.forEach((a: any, idx: number) => {
      if (
        String((a.type || '')).toLowerCase() === 'time' &&
        failIndex < 0
      ) {
        failIndex = 1 + idx
      }
    })
  }
  if (failIndex < 0) {
    failIndex = steps.length - 1
  }
  return steps.map((s, idx) => {
    if (idx < failIndex) {
      return {
        ...s,
        status: 'success',
        error: false
      }
    }
    if (idx === failIndex) {
      return {
        ...s,
        status: 'failed',
        error: true
      }
    }
    return {
      ...s,
      status: 'failed',
      error: false
    }
  })
}

function buildWebSteps(
  content: unknown,
  executedCount: number,
  isSuccess: boolean
): ExecutionStep[] {
  let script = ''
  if (typeof content === 'string') {
    script = content
  } else if (content && typeof content === 'object') {
    const anyContent = content as any
    if (typeof anyContent.script === 'string') {
      script = anyContent.script
    }
  }
  const lines = script
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
  const steps: ExecutionStep[] = lines.map((line, idx) => {
    const original = line
    let action = ''
    let details = ''
    if (line.startsWith('打开URL:')) {
      const url = line.split(':', 1)[0] ? line.split(':', 2)[1] || '' : ''
      action = '打开页面'
      details = url.trim()
    } else if (line.startsWith('刷新页面')) {
      action = '刷新页面'
      details = ''
    } else if (/click\(/i.test(line) || line.startsWith('点击元素') || /点击/i.test(line)) {
      action = '点击元素'
      details = line
    } else if (/input/i.test(line) || /send_keys/i.test(line) || /输入/.test(line)) {
      action = '输入文本'
      details = line
    } else if (/assert/i.test(line) || /断言/.test(line)) {
      action = '断言'
      details = line
    } else if (/wait/i.test(line) || /sleep/i.test(line) || /等待/.test(line)) {
      action = '等待'
      details = line
    } else {
      action = original.length > 40 ? `${original.slice(0, 40)}...` : original
      details = original
    }
    return {
      step: idx + 1,
      action,
      status: 'success',
      time: '',
      details: details || action,
      error: false
    }
  })
  return applyStepStatuses(steps, executedCount, isSuccess)
}

function buildAppSteps(
  content: unknown,
  executedCount: number,
  isSuccess: boolean
): ExecutionStep[] {
  if (!content || typeof content !== 'object') {
    return []
  }
  const anyContent = content as any
  const rawSteps = Array.isArray(anyContent.steps) ? anyContent.steps : []
  const steps: ExecutionStep[] = rawSteps.map((s: any, idx: number) => {
    const actionType = String(s?.action || '').toLowerCase()
    const by = s?.by ? String(s.by) : ''
    const value =
      s?.value || s?.selector || s?.xpath || s?.path || s?.file || s?.name || ''
    const text = s?.text ? String(s.text) : ''
    let action = ''
    let details = ''
    if (actionType === 'click') {
      action = '点击元素'
      details = value ? `${by || 'selector'}: ${value}` : ''
    } else if (actionType === 'input') {
      action = '输入文本'
      details = text ? `输入 "${text}"` : ''
    } else if (actionType === 'wait') {
      action = '等待元素'
      const ms = s?.ms != null ? Number(s.ms) : 1000
      details = `等待 ${ms} ms`
    } else if (actionType === 'back') {
      action = '返回'
    } else if (actionType === 'launch') {
      action = '启动应用'
    } else if (actionType === 'close') {
      action = '关闭应用'
    } else if (actionType === 'screenshot') {
      action = '截图'
      details = value ? String(value) : 'screenshot.png'
    } else if (actionType === 'assert_exists') {
      action = '断言元素存在'
      details = value ? `${by || 'selector'}: ${value}` : ''
    } else {
      action = actionType || '步骤'
    }
    const detailText = details || action
    return {
      step: idx + 1,
      action,
      status: 'success',
      time: '',
      details: detailText,
      error: false
    }
  })
  return applyStepStatuses(steps, executedCount, isSuccess)
}

const executionSteps = computed<ExecutionStep[]>(() => {
  const r = report.value
  const tc = testCase.value
  const caseType = (tc?.type || r?.caseType || '').toUpperCase()
  const status = (r?.status || '').toLowerCase()
  const isSuccess = status === 'success'
  const executedCount = logLines.value.length

  if (caseType === 'API') {
    const content = parsedCaseContent.value
    return buildApiSteps(content as any, isSuccess, apiErrorText.value)
  }

  if (caseType === 'WEB') {
    const content = parsedCaseContent.value
    return buildWebSteps(content, executedCount, isSuccess)
  }

  if (caseType === 'APP') {
    const content = parsedCaseContent.value
    return buildAppSteps(content, executedCount, isSuccess)
  }

  if (!consoleLogs.value.length) {
    return []
  }
  return consoleLogs.value.map((log, index) => ({
    step: index + 1,
    action: log.message,
    status: log.level === 'error' ? 'failed' : 'success',
    time: '',
    details: log.message,
    error: log.level === 'error'
  }))
})

const reportData = computed(() => {
  const r = report.value
  const status = r?.status || 'failed'
  const caseName =
    r?.caseName || (r?.caseId ? `测试用例 #${r.caseId}` : '测试报告')
  const executionTime = r?.executedAt
    ? String(r.executedAt).replace('T', ' ')
    : ''
  const duration =
    typeof r?.executionTime === 'number' && r.executionTime >= 0
      ? `${r.executionTime}ms`
      : '-'
  const engine = r?.executedBy || 'System'
  const environment = r?.environment || ''

  const totalSteps =
    executionSteps.value.length > 0 ? executionSteps.value.length : 1
  const failedSteps = executionSteps.value.filter(
    (item) => item.status === 'failed'
  ).length
  const passedSteps =
    totalSteps - failedSteps >= 0 ? totalSteps - failedSteps : 0

  return {
    status,
    caseName,
    executionTime,
    duration,
    engine,
    environment,
    totalSteps,
    passedSteps,
    failedSteps
  }
})

const fetchReport = async () => {
  const id = route.params.id as string
  if (!id) {
    return
  }
  try {
    const res = await request.get(`/reports/${id}`)
    const detail = res as ReportDetail
    report.value = detail
    if (detail.caseId) {
      try {
        const caseRes = await request.get(`/testcases/${detail.caseId}`)
        testCase.value = caseRes as RawTestCase
      } catch (e) {
        console.error(e)
      }
    }
  } catch (e) {
    console.error(e)
  }
}

onMounted(fetchReport)
</script>

<template>
  <div class="p-6 space-y-6">
    <!-- Report Header -->
    <Card class="border-gray-200">
      <CardContent class="pt-6">
        <div class="flex items-start justify-between mb-6">
          <div>
            <div class="flex items-center gap-3 mb-2">
              <h2 class="text-2xl font-semibold text-gray-900">{{ reportData.caseName }}</h2>
              <Badge v-if="reportData.status === 'success'" class="bg-green-500 text-white px-3 py-1">
                <CheckCircle class="w-4 h-4 mr-1" />
                PASS
              </Badge>
              <Badge v-else class="bg-red-500 text-white px-3 py-1">
                <XCircle class="w-4 h-4 mr-1" />
                FAIL
              </Badge>
            </div>
            <div class="flex items-center gap-4 text-sm text-gray-600">
              <span class="flex items-center gap-1">
                <Clock class="w-4 h-4" />
                {{ reportData.executionTime }}
              </span>
              <span>耗时: {{ reportData.duration }}</span>
              <span>引擎: {{ reportData.engine }}</span>
              <span>环境: {{ reportData.environment }}</span>
            </div>
          </div>
          <div class="flex gap-2">
            <Button variant="outline" size="sm" class="border-gray-300">
              <Download class="w-4 h-4 mr-2" />
              导出报告
            </Button>
            <Button variant="outline" size="sm" class="border-gray-300">
              <Share2 class="w-4 h-4 mr-2" />
              分享
            </Button>
          </div>
        </div>

        <!-- Statistics -->
        <div class="grid grid-cols-4 gap-4 p-4 bg-gray-50 rounded-lg">
          <div class="text-center">
            <div class="text-2xl font-semibold text-gray-900">{{ reportData.totalSteps }}</div>
            <div class="text-sm text-gray-600 mt-1">总步骤数</div>
          </div>
          <div class="text-center">
            <div class="text-2xl font-semibold text-green-600">{{ reportData.passedSteps }}</div>
            <div class="text-sm text-gray-600 mt-1">通过步骤</div>
          </div>
          <div class="text-center">
            <div class="text-2xl font-semibold text-red-600">{{ reportData.failedSteps }}</div>
            <div class="text-sm text-gray-600 mt-1">失败步骤</div>
          </div>
          <div class="text-center">
            <div class="text-2xl font-semibold text-blue-600">
              {{ Math.round((reportData.passedSteps / reportData.totalSteps) * 100) }}%
            </div>
            <div class="text-sm text-gray-600 mt-1">通过率</div>
          </div>
        </div>
      </CardContent>
    </Card>

    <div class="grid grid-cols-2 gap-6">
      <!-- Left Column - Execution Steps Timeline -->
      <Card class="border-gray-200">
        <CardContent class="pt-6">
          <h3 class="font-semibold text-gray-900 mb-4">执行步骤时间线</h3>
          <div class="space-y-3 max-h-[600px] overflow-y-auto">
            <div
              v-for="step in executionSteps"
              :key="step.step"
              :class="`relative pl-8 pb-3 border-l-2 ${
                step.status === 'success'
                  ? 'border-green-500'
                  : 'border-red-500'
              }`"
            >
              <!-- Step indicator -->
              <div
                :class="`absolute left-[-9px] top-0 w-4 h-4 rounded-full border-2 ${
                  step.status === 'success'
                    ? 'bg-green-500 border-green-500'
                    : 'bg-red-500 border-red-500'
                }`"
              />
              
              <div class="space-y-1">
                <div class="flex items-start justify-between">
                  <div class="flex-1">
                    <div class="flex items-center gap-2">
                      <span class="text-xs text-gray-500">步骤 {{ step.step }}</span>
                      <CheckCircle v-if="step.status === 'success'" class="w-4 h-4 text-green-500" />
                      <XCircle v-else class="w-4 h-4 text-red-500" />
                    </div>
                    <div class="font-medium text-sm text-gray-900 mt-1">
                      {{ step.action }}
                    </div>
                    <div class="text-xs text-gray-600 mt-1">
                      {{ step.details }}
                    </div>
                  </div>
                  <span class="text-xs text-gray-500">{{ step.time }}</span>
                </div>
                
                <div v-if="step.error" class="mt-2 p-2 bg-red-50 border border-red-200 rounded text-xs text-red-800">
                  <div class="flex items-start gap-1">
                    <AlertCircle class="w-3 h-3 mt-0.5 flex-shrink-0" />
                    <span>{{ step.details }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Right Column - Console Logs & Screenshot -->
      <div class="space-y-6">
        <!-- Console Logs -->
        <Card class="border-gray-200">
          <CardContent class="pt-6">
            <h3 class="font-semibold text-gray-900 mb-4">控制台日志</h3>
            <div class="bg-gray-900 text-green-400 p-4 rounded font-mono text-xs h-[300px] overflow-y-auto">
              <div
                v-for="(log, index) in consoleLogs"
                :key="index"
                :class="`mb-1 ${
                  log.level === 'error'
                    ? 'text-red-400'
                    : log.level === 'success'
                    ? 'text-green-400'
                    : 'text-gray-400'
                }`"
              >
                <span class="text-gray-500">[{{ log.time }}]</span> {{ log.message }}
              </div>
            </div>
          </CardContent>
        </Card>

        <!-- Error Screenshot -->
        <Card class="border-gray-200 border-red-300">
          <CardContent class="pt-6">
            <h3 class="font-semibold text-gray-900 mb-4 flex items-center gap-2">
              <AlertCircle class="w-5 h-5 text-red-500" />
              错误截图
            </h3>
            <div class="bg-gray-100 border-2 border-dashed border-gray-300 rounded p-8 text-center">
              <div class="space-y-3">
                <div class="w-16 h-16 bg-gray-300 rounded-lg mx-auto flex items-center justify-center">
                  <svg class="w-8 h-8 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                </div>
                <div>
                  <p class="text-sm text-gray-600 mb-2">payment_result.png</p>
                  <p class="text-xs text-gray-500">
                    错误发生时的页面截图
                  </p>
                </div>
                <Button size="sm" variant="outline" class="border-gray-300">
                  <Download class="w-4 h-4 mr-2" />
                  下载截图
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</template>

// src/app/components/ReportDetail.tsx
import React from 'react';
import { Card, CardContent } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { CheckCircle, XCircle, Clock, Download, Share2, AlertCircle } from 'lucide-react';

export function ReportDetail() {
  const reportData = {
    status: 'failed',
    caseName: 'Web支付流程测试',
    executionTime: '2026-01-02 15:30:25',
    duration: '15.8s',
    engine: '本地引擎-张三',
    environment: 'staging',
    totalSteps: 12,
    passedSteps: 10,
    failedSteps: 2
  };

  const executionSteps = [
    { step: 1, action: '打开浏览器', status: 'success', time: '0.5s', details: 'Chrome 120.0.0' },
    { step: 2, action: '访问URL: https://example.com/checkout', status: 'success', time: '1.2s', details: '页面加载成功' },
    { step: 3, action: '等待元素: #product-list', status: 'success', time: '0.3s', details: '元素已出现' },
    { step: 4, action: '点击元素: .add-to-cart', status: 'success', time: '0.2s', details: '商品已添加到购物车' },
    { step: 5, action: '点击元素: .checkout-btn', status: 'success', time: '0.3s', details: '进入结算页面' },
    { step: 6, action: '等待元素: #payment-form', status: 'success', time: '0.8s', details: '支付表单已加载' },
    { step: 7, action: '输入文本: #card-number, 4111111111111111', status: 'success', time: '0.5s', details: '卡号输入完成' },
    { step: 8, action: '输入文本: #cvv, 123', status: 'success', time: '0.2s', details: 'CVV输入完成' },
    { step: 9, action: '点击元素: #submit-payment', status: 'success', time: '0.4s', details: '提交支付请求' },
    { step: 10, action: '等待元素: .payment-result', status: 'success', time: '3.5s', details: '等待支付响应' },
    { step: 11, action: '断言文本: .payment-status, 支付成功', status: 'failed', time: '0.1s', details: '期望: "支付成功", 实际: "支付处理中"', error: true },
    { step: 12, action: '截图: payment_result.png', status: 'failed', time: '0.2s', details: '由于上一步失败，测试中止', error: true }
  ];

  const consoleLogs = [
    { time: '15:30:25.123', level: 'info', message: '[TestEngine] 开始执行测试用例: Web支付流程测试' },
    { time: '15:30:25.456', level: 'info', message: '[Browser] 启动Chrome浏览器...' },
    { time: '15:30:26.001', level: 'success', message: '[Step 1] ✓ 打开浏览器' },
    { time: '15:30:26.234', level: 'info', message: '[Navigator] 访问 https://example.com/checkout' },
    { time: '15:30:27.456', level: 'success', message: '[Step 2] ✓ 访问URL成功' },
    { time: '15:30:27.789', level: 'success', message: '[Step 3] ✓ 元素已找到: #product-list' },
    { time: '15:30:28.012', level: 'success', message: '[Step 4] ✓ 点击成功: .add-to-cart' },
    { time: '15:30:28.345', level: 'success', message: '[Step 5] ✓ 点击成功: .checkout-btn' },
    { time: '15:30:29.123', level: 'success', message: '[Step 6] ✓ 支付表单已加载' },
    { time: '15:30:29.678', level: 'success', message: '[Step 7] ✓ 卡号输入完成' },
    { time: '15:30:29.890', level: 'success', message: '[Step 8] ✓ CVV输入完成' },
    { time: '15:30:30.234', level: 'success', message: '[Step 9] ✓ 提交支付请求' },
    { time: '15:30:33.789', level: 'success', message: '[Step 10] ✓ 支付响应已返回' },
    { time: '15:30:33.890', level: 'error', message: '[Step 11] ✗ 断言失败: 文本不匹配' },
    { time: '15:30:33.891', level: 'error', message: '[Assertion] 期望值: "支付成功"' },
    { time: '15:30:33.892', level: 'error', message: '[Assertion] 实际值: "支付处理中"' },
    { time: '15:30:34.001', level: 'error', message: '[TestEngine] 测试失败，中止执行' },
    { time: '15:30:34.123', level: 'info', message: '[Browser] 关闭浏览器' },
    { time: '15:30:34.234', level: 'info', message: '[TestEngine] 生成测试报告' }
  ];

  return (
    <div className="p-6 space-y-6">
      {/* Report Header */}
      <Card className="border-gray-200">
        <CardContent className="pt-6">
          <div className="flex items-start justify-between mb-6">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <h2 className="text-2xl font-semibold text-gray-900">{reportData.caseName}</h2>
                {reportData.status === 'success' ? (
                  <Badge className="bg-green-500 text-white px-3 py-1">
                    <CheckCircle className="w-4 h-4 mr-1" />
                    PASS
                  </Badge>
                ) : (
                  <Badge className="bg-red-500 text-white px-3 py-1">
                    <XCircle className="w-4 h-4 mr-1" />
                    FAIL
                  </Badge>
                )}
              </div>
              <div className="flex items-center gap-4 text-sm text-gray-600">
                <span className="flex items-center gap-1">
                  <Clock className="w-4 h-4" />
                  {reportData.executionTime}
                </span>
                <span>耗时: {reportData.duration}</span>
                <span>引擎: {reportData.engine}</span>
                <span>环境: {reportData.environment}</span>
              </div>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" className="border-gray-300">
                <Download className="w-4 h-4 mr-2" />
                导出报告
              </Button>
              <Button variant="outline" size="sm" className="border-gray-300">
                <Share2 className="w-4 h-4 mr-2" />
                分享
              </Button>
            </div>
          </div>

          {/* Statistics */}
          <div className="grid grid-cols-4 gap-4 p-4 bg-gray-50 rounded-lg">
            <div className="text-center">
              <div className="text-2xl font-semibold text-gray-900">{reportData.totalSteps}</div>
              <div className="text-sm text-gray-600 mt-1">总步骤数</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-semibold text-green-600">{reportData.passedSteps}</div>
              <div className="text-sm text-gray-600 mt-1">通过步骤</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-semibold text-red-600">{reportData.failedSteps}</div>
              <div className="text-sm text-gray-600 mt-1">失败步骤</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-semibold text-blue-600">
                {Math.round((reportData.passedSteps / reportData.totalSteps) * 100)}%
              </div>
              <div className="text-sm text-gray-600 mt-1">通过率</div>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-2 gap-6">
        {/* Left Column - Execution Steps Timeline */}
        <Card className="border-gray-200">
          <CardContent className="pt-6">
            <h3 className="font-semibold text-gray-900 mb-4">执行步骤时间线</h3>
            <div className="space-y-3 max-h-[600px] overflow-y-auto">
              {executionSteps.map((step) => (
                <div
                  key={step.step}
                  className={`relative pl-8 pb-3 border-l-2 ${
                    step.status === 'success'
                      ? 'border-green-500'
                      : 'border-red-500'
                  }`}
                >
                  {/* Step indicator */}
                  <div
                    className={`absolute left-[-9px] top-0 w-4 h-4 rounded-full border-2 ${
                      step.status === 'success'
                        ? 'bg-green-500 border-green-500'
                        : 'bg-red-500 border-red-500'
                    }`}
                  />
                  
                  <div className="space-y-1">
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <span className="text-xs text-gray-500">步骤 {step.step}</span>
                          {step.status === 'success' ? (
                            <CheckCircle className="w-4 h-4 text-green-500" />
                          ) : (
                            <XCircle className="w-4 h-4 text-red-500" />
                          )}
                        </div>
                        <div className="font-medium text-sm text-gray-900 mt-1">
                          {step.action}
                        </div>
                        <div className="text-xs text-gray-600 mt-1">
                          {step.details}
                        </div>
                      </div>
                      <span className="text-xs text-gray-500">{step.time}</span>
                    </div>
                    
                    {step.error && (
                      <div className="mt-2 p-2 bg-red-50 border border-red-200 rounded text-xs text-red-800">
                        <div className="flex items-start gap-1">
                          <AlertCircle className="w-3 h-3 mt-0.5 flex-shrink-0" />
                          <span>{step.details}</span>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Right Column - Console Logs & Screenshot */}
        <div className="space-y-6">
          {/* Console Logs */}
          <Card className="border-gray-200">
            <CardContent className="pt-6">
              <h3 className="font-semibold text-gray-900 mb-4">控制台日志</h3>
              <div className="bg-gray-900 text-green-400 p-4 rounded font-mono text-xs h-[300px] overflow-y-auto">
                {consoleLogs.map((log, index) => (
                  <div
                    key={index}
                    className={`mb-1 ${
                      log.level === 'error'
                        ? 'text-red-400'
                        : log.level === 'success'
                        ? 'text-green-400'
                        : 'text-gray-400'
                    }`}
                  >
                    <span className="text-gray-500">[{log.time}]</span> {log.message}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Error Screenshot */}
          <Card className="border-gray-200 border-red-300">
            <CardContent className="pt-6">
              <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <AlertCircle className="w-5 h-5 text-red-500" />
                错误截图
              </h3>
              <div className="bg-gray-100 border-2 border-dashed border-gray-300 rounded p-8 text-center">
                <div className="space-y-3">
                  <div className="w-16 h-16 bg-gray-300 rounded-lg mx-auto flex items-center justify-center">
                    <svg className="w-8 h-8 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-2">payment_result.png</p>
                    <p className="text-xs text-gray-500">
                      错误发生时的页面截图
                    </p>
                  </div>
                  <Button size="sm" variant="outline" className="border-gray-300">
                    <Download className="w-4 h-4 mr-2" />
                    下载截图
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
